apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-front
  template:
    metadata:
      labels:
        app: demo-front
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: front
          image: ghcr.io/organization-demo-task/demo-front:v0.1.1-dev
          ports:
            - containerPort: 80
