apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-back
  template:
    metadata:
      labels:
        app: demo-back
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: back
          image: ghcr.io/organization-demo-task/demo-back:v0.1.0-dev
          ports:
            - containerPort: 8000
